//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class templateTable
    {
        public int TemplateId { get; set; }
        public string TemplateType { get; set; }
        public string TemplateTitle { get; set; }
        public string TemplateName { get; set; }
        public string TemplateBody { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
